import type { CourseDefinition, EvidenceReference, Program, StudentProfile } from "@/lib/domain";

export const evidence: EvidenceReference[] = [
  {
    id: "coc-math-2025",
    institutionId: "coc",
    title: "College of the Canyons 2025-26 Catalog",
    url: "https://www.canyons.edu/_documents/administration/academicaffairs/collegecatalog/2025-26-Catalog-508.pdf",
    effectiveYear: "2025-26",
    retrievedAt: "2026-07-13",
    provenance: "official",
    status: "verified",
    note: "Supports College of the Canyons course titles, units, and the MATH 104 -> 211 -> 212 calculus sequence.",
  },
  {
    id: "coc-cs-current",
    institutionId: "coc",
    title: "College of the Canyons Computer Science Department",
    url: "https://www.canyons.edu/academics/computerscience/",
    effectiveYear: "Current page retrieved 2026",
    retrievedAt: "2026-07-13",
    provenance: "official",
    status: "verified",
    note: "Supports the existence and names of COMP SCI 111, 182, and 256.",
  },
  {
    id: "coc-stats-current",
    institutionId: "coc",
    title: "College of the Canyons Math and Statistics Courses",
    url: "https://www.canyons.edu/academics/mathematics/math-courses.php",
    effectiveYear: "2025-26",
    retrievedAt: "2026-07-13",
    provenance: "official",
    status: "verified",
    note: "Supports STAT C1000 (formerly MATH 140) as a four-unit introductory statistics course.",
  },
  {
    id: "assist-review",
    institutionId: "coc",
    title: "ASSIST — California articulation source",
    url: "https://assist.org/",
    effectiveYear: "2025-26",
    retrievedAt: "2026-07-13",
    provenance: "assist",
    status: "partial",
    note: "Specific institution-to-institution articulation must be confirmed in ASSIST before enrollment decisions.",
  },
  {
    id: "berkeley-cogsci",
    institutionId: "berkeley",
    pathwayId: "berkeley-cogsci",
    title: "UC Berkeley Cognitive Science Degree Requirements",
    url: "https://cogsci.berkeley.edu/undergraduate-program/major-program/degree-requirements",
    effectiveYear: "Current requirements retrieved 2026",
    retrievedAt: "2026-07-13",
    provenance: "official",
    status: "verified",
    note: "Supports calculus, statistical thinking, programming, discrete math, and neuroscience preparation categories.",
  },
  {
    id: "berkeley-data",
    institutionId: "berkeley",
    pathwayId: "berkeley-data",
    title: "UC Berkeley Data Science — Prospective Transfer Students",
    url: "https://cdss.berkeley.edu/dsus/prospectivetransfers",
    effectiveYear: "Fall 2026 transfer guidance",
    retrievedAt: "2026-07-13",
    provenance: "official",
    status: "verified",
    note: "Supports Calculus I, Calculus II, and Linear Algebra preparation and recommends computing preparation.",
  },
  {
    id: "ucla-majors",
    institutionId: "ucla",
    title: "UCLA Undergraduate Majors",
    url: "https://admission.ucla.edu/apply/majors",
    effectiveYear: "2026",
    retrievedAt: "2026-07-13",
    provenance: "official",
    status: "verified",
    note: "Supports the official Cognitive Science B.S. and Statistics and Data Science B.S. program names.",
  },
  {
    id: "ucla-cogsci",
    institutionId: "ucla",
    pathwayId: "ucla-cogsci",
    title: "UCLA Transfer Preparation Requirements — Cognitive Science",
    url: "https://admission.ucla.edu/apply/transfer/deciding-on-major/major-preparation-the-college/requirements-for-cognitive-science",
    effectiveYear: "Current transfer guidance retrieved 2026",
    retrievedAt: "2026-07-13",
    provenance: "official",
    status: "verified",
    note: "Supports one year of calculus, introductory C++, and four or more additional preparation courses across psychology, biology, physical science or linguistics, philosophy, and further programming.",
  },
  {
    id: "ucla-data",
    institutionId: "ucla",
    pathwayId: "ucla-data",
    title: "UCLA Statistics & Data Science Major Worksheet",
    url: "https://statistics.ucla.edu/index.php/academics/undergraduate/statistics-major-worksheets/",
    effectiveYear: "Current page retrieved 2026",
    retrievedAt: "2026-07-13",
    provenance: "official",
    status: "verified",
    note: "Supports statistics, programming, calculus, multivariable calculus, and linear algebra preparation groups.",
  },
  {
    id: "ucsd-cogsci",
    institutionId: "ucsd",
    pathwayId: "ucsd-cogsci",
    title: "UC San Diego Cognitive Science Transfer Students",
    url: "https://cogsci.ucsd.edu/undergraduates/prospectives/transfer-students.html",
    effectiveYear: "Current transfer guidance retrieved 2026",
    retrievedAt: "2026-07-13",
    provenance: "official",
    status: "verified",
    note: "Supports B.S. math, statistics, research methods, neurobiology, and programming preparation.",
  },
  {
    id: "ucsd-data",
    institutionId: "ucsd",
    pathwayId: "ucsd-data",
    title: "UC San Diego Data Science Prospective Transfer Students",
    url: "https://datascience.ucsd.edu/prospective-students/prospective-transfer-students/",
    effectiveYear: "2026 transfer guidance",
    retrievedAt: "2026-07-13",
    provenance: "official",
    status: "verified",
    note: "Supports linear algebra, three-term calculus preparation, and programming as transfer preparation.",
  },
];

export const courses: CourseDefinition[] = [
  { id: "coc-engl-c1000", institutionId: "coc", code: "ENGL C1000", title: "Academic Reading and Writing", units: 4, category: "general", prerequisites: [], offeredTerms: ["fall", "spring", "summer"], evidenceIds: ["coc-math-2025"] },
  { id: "coc-engl-c1001", institutionId: "coc", code: "ENGL C1001", title: "Critical Thinking and Writing", units: 4, category: "general", prerequisites: ["coc-engl-c1000"], offeredTerms: ["fall", "spring"], evidenceIds: ["coc-math-2025"] },
  { id: "coc-psych-101", institutionId: "coc", code: "PSYCH 101", title: "Introduction to Psychology", units: 3, category: "major", prerequisites: [], offeredTerms: ["fall", "spring", "summer"], evidenceIds: ["coc-math-2025", "assist-review"] },
  { id: "coc-soci-101", institutionId: "coc", code: "SOCI 101", title: "Introduction to Sociology", units: 3, category: "general", prerequisites: [], offeredTerms: ["fall", "spring"], evidenceIds: ["coc-math-2025", "assist-review"] },
  { id: "coc-phil-106", institutionId: "coc", code: "PHIL 106", title: "Critical Thinking", units: 3, category: "general", prerequisites: [], offeredTerms: ["fall", "spring"], evidenceIds: ["coc-math-2025", "assist-review"] },
  { id: "coc-biol-101", institutionId: "coc", code: "BIOSCI 101", title: "General Biology", units: 4, category: "science", prerequisites: [], offeredTerms: ["fall", "spring"], evidenceIds: ["coc-math-2025", "assist-review"] },
  { id: "coc-math-103", institutionId: "coc", code: "MATH 103", title: "College Algebra", units: 5, category: "math", prerequisites: [], offeredTerms: ["fall", "spring", "summer"], evidenceIds: ["coc-math-2025"] },
  { id: "coc-math-104", institutionId: "coc", code: "MATH 104", title: "Precalculus", units: 5, category: "math", prerequisites: ["coc-math-103"], offeredTerms: ["fall", "spring", "summer"], evidenceIds: ["coc-math-2025"] },
  { id: "coc-math-211", institutionId: "coc", code: "MATH 211", title: "Calculus I", units: 5, category: "math", prerequisites: ["coc-math-104"], offeredTerms: ["fall", "spring", "summer"], evidenceIds: ["coc-math-2025", "assist-review"] },
  { id: "coc-math-212", institutionId: "coc", code: "MATH 212", title: "Calculus II", units: 5, category: "math", prerequisites: ["coc-math-211"], offeredTerms: ["fall", "spring", "summer"], evidenceIds: ["coc-math-2025", "assist-review"] },
  { id: "coc-math-213", institutionId: "coc", code: "MATH 213", title: "Calculus III", units: 5, category: "math", prerequisites: ["coc-math-212"], offeredTerms: ["fall", "spring", "summer"], evidenceIds: ["coc-math-2025", "assist-review"] },
  { id: "coc-math-214", institutionId: "coc", code: "MATH 214", title: "Linear Algebra", units: 4, category: "math", prerequisites: ["coc-math-212"], offeredTerms: ["fall", "spring"], evidenceIds: ["coc-math-2025", "assist-review"] },
  { id: "coc-stat-c1000", institutionId: "coc", code: "STAT C1000", title: "Introduction to Statistics", units: 4, category: "math", prerequisites: ["coc-math-103"], offeredTerms: ["fall", "spring", "summer"], evidenceIds: ["coc-stats-current", "assist-review"] },
  { id: "coc-compsci-111", institutionId: "coc", code: "COMP SCI 111", title: "Introduction to Algorithms and Programming: Java", units: 4, category: "programming", prerequisites: [], offeredTerms: ["fall", "spring"], evidenceIds: ["coc-math-2025", "coc-cs-current", "assist-review"] },
  { id: "coc-compsci-182", institutionId: "coc", code: "COMP SCI 182", title: "Data Structures and Program Design", units: 4, category: "programming", prerequisites: ["coc-compsci-111"], offeredTerms: ["fall", "spring"], evidenceIds: ["coc-math-2025", "coc-cs-current", "assist-review"] },
  { id: "coc-compsci-256", institutionId: "coc", code: "COMP SCI 256", title: "Discrete Structures", units: 3, category: "programming", prerequisites: ["coc-compsci-111"], offeredTerms: ["fall", "spring"], evidenceIds: ["coc-math-2025", "coc-cs-current", "assist-review"] },
  { id: "coc-research", institutionId: "coc", code: "PSYCH 205", title: "Research Methods in Psychology", units: 3, category: "major", prerequisites: ["coc-stat-c1000"], offeredTerms: ["fall", "spring"], evidenceIds: ["coc-math-2025", "assist-review"] },
];

function requirement(id: string, label: string, courseId: string, pathwayEvidenceId: string): Program["requirements"][number] {
  return { id, label, courseIds: [courseId], minimumCount: 1, minimumGrade: "C-", evidenceIds: [pathwayEvidenceId, "assist-review"] };
}

export const programs: Program[] = [
  { id: "berkeley-cogsci", universityId: "berkeley", universityName: "UC Berkeley", name: "Cognitive Science", degree: "B.A.", family: "cognitive-science", evidenceIds: ["berkeley-cogsci"], requirements: [requirement("stats", "Statistical thinking", "coc-stat-c1000", "berkeley-cogsci"), requirement("calculus", "Calculus", "coc-math-211", "berkeley-cogsci"), requirement("programming", "Computer programming", "coc-compsci-111", "berkeley-cogsci"), requirement("discrete", "Discrete mathematics", "coc-compsci-256", "berkeley-cogsci"), requirement("neuroscience", "Neuroscience preparation — exact course review", "coc-biol-101", "berkeley-cogsci")] },
  { id: "berkeley-data", universityId: "berkeley", universityName: "UC Berkeley", name: "Data Science", degree: "B.A.", family: "data-science", evidenceIds: ["berkeley-data"], requirements: [requirement("calc-1", "Calculus I", "coc-math-211", "berkeley-data"), requirement("calc-2", "Calculus II", "coc-math-212", "berkeley-data"), requirement("linear", "Linear algebra", "coc-math-214", "berkeley-data"), requirement("programming", "Recommended computing preparation", "coc-compsci-111", "berkeley-data")] },
  { id: "ucla-cogsci", universityId: "ucla", universityName: "UCLA", name: "Cognitive Science", degree: "B.S.", family: "cognitive-science", evidenceIds: ["ucla-majors", "ucla-cogsci"], requirements: [requirement("calc-1", "First calculus course", "coc-math-211", "ucla-cogsci"), requirement("calc-2", "Second calculus course", "coc-math-212", "ucla-cogsci"), requirement("programming", "Introductory programming — language equivalency review", "coc-compsci-111", "ucla-cogsci"), requirement("psych", "Introductory psychology", "coc-psych-101", "ucla-cogsci"), requirement("biology", "Additional preparation: biology", "coc-biol-101", "ucla-cogsci"), requirement("philosophy", "Additional preparation: critical reasoning", "coc-phil-106", "ucla-cogsci"), requirement("further-programming", "Additional preparation: further programming", "coc-compsci-182", "ucla-cogsci")] },
  { id: "ucla-data", universityId: "ucla", universityName: "UCLA", name: "Statistics and Data Science", degree: "B.S.", family: "data-science", evidenceIds: ["ucla-majors", "ucla-data"], requirements: [requirement("stats", "Introductory statistics", "coc-stat-c1000", "ucla-data"), requirement("programming", "Statistics programming preparation — exact course review", "coc-compsci-111", "ucla-data"), requirement("calc-1", "Calculus I", "coc-math-211", "ucla-data"), requirement("calc-2", "Calculus II", "coc-math-212", "ucla-data"), requirement("calc-3", "Multivariable calculus sequence — exact articulation review", "coc-math-213", "ucla-data"), requirement("linear", "Linear algebra", "coc-math-214", "ucla-data")] },
  { id: "ucsd-cogsci", universityId: "ucsd", universityName: "UC San Diego", name: "Cognitive Science", degree: "B.S.", family: "cognitive-science", evidenceIds: ["ucsd-cogsci"], requirements: [requirement("calc-1", "Calculus I", "coc-math-211", "ucsd-cogsci"), requirement("calc-2", "Calculus II", "coc-math-212", "ucsd-cogsci"), requirement("linear", "Linear algebra", "coc-math-214", "ucsd-cogsci"), requirement("stats", "Statistical analysis", "coc-stat-c1000", "ucsd-cogsci"), requirement("research", "Research methods", "coc-research", "ucsd-cogsci"), requirement("neuroscience", "Neurobiology preparation — exact course review", "coc-biol-101", "ucsd-cogsci"), requirement("programming", "Programming", "coc-compsci-111", "ucsd-cogsci")] },
  { id: "ucsd-data", universityId: "ucsd", universityName: "UC San Diego", name: "Data Science", degree: "B.S.", family: "data-science", evidenceIds: ["ucsd-data"], requirements: [requirement("linear", "Linear algebra", "coc-math-214", "ucsd-data"), requirement("calc-1", "Calculus I", "coc-math-211", "ucsd-data"), requirement("calc-2", "Calculus II", "coc-math-212", "ucsd-data"), requirement("calc-3", "Calculus III", "coc-math-213", "ucsd-data"), requirement("programming", "Programming", "coc-compsci-111", "ucsd-data")] },
];

export const seedProfile: StudentProfile = {
  id: "jordan-lee",
  name: "Jordan Lee",
  originInstitutionId: "coc",
  originInstitutionName: "College of the Canyons",
  selectedPathwayId: "ucla-data",
  selectedPathwayIds: programs.map((program) => program.id),
  maxUnits: 15,
  summerEnrollment: false,
  courses: [
    { courseId: "coc-engl-c1000", code: "ENGL C1000", title: "Academic Reading and Writing", units: 4, grade: "A", term: "Fall 2025", status: "completed", matchStatus: "verified", sourceLabel: "Transcript page 1" },
    { courseId: "coc-psych-101", code: "PSYCH 101", title: "Introduction to Psychology", units: 3, grade: "B+", term: "Fall 2025", status: "completed", matchStatus: "verified", sourceLabel: "Transcript page 1" },
    { courseId: "coc-math-103", code: "MATH 103", title: "College Algebra", units: 5, grade: "A-", term: "Fall 2025", status: "completed", matchStatus: "verified", sourceLabel: "Transcript page 1" },
    { courseId: "coc-compsci-111", code: "COMP SCI 111", title: "Introduction to Algorithms and Programming: Java", units: 4, grade: "B", term: "Spring 2026", status: "completed", matchStatus: "verified", sourceLabel: "Transcript page 2" },
    { courseId: "coc-soci-101", code: "SOCI 101", title: "Introduction to Sociology", units: 3, grade: "A", term: "Spring 2026", status: "completed", matchStatus: "verified", sourceLabel: "Transcript page 2" },
    { courseId: "coc-biol-101", code: "BIOSCI 101", title: "General Biology", units: 4, grade: "B+", term: "Spring 2026", status: "completed", matchStatus: "verified", sourceLabel: "Transcript page 3" },
    { courseId: "coc-math-211", code: "MATH 211", title: "Calculus I", units: 5, term: "Spring 2027", status: "planned", matchStatus: "uncertain", sourceLabel: "Transcript page 2 — planned course" },
  ],
};

export const courseById = new Map(courses.map((course) => [course.id, course]));
export const programById = new Map(programs.map((program) => [program.id, program]));
export const evidenceById = new Map(evidence.map((item) => [item.id, item]));
